parameters:
  extRepoUrl : ''
  extRepoDir : ''
  HelperBranch : 'master'

jobs:
  - job:
    displayName: Code Sign and Verify
    pool: 
      name: TestSuiteESRPCodeSignPool
    workspace:
      clean: false
    timeoutInMinutes: 0

    steps:
      - task: CopyFiles@2
        displayName: 'Copy TestSuite'
        inputs:
          SourceFolder: '$(Build.Repository.LocalPath)'
          TargetFolder: '$(Build.BinariesDirectory)'
          CleanTargetFolder: true

      - script: 'git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" -b %HelperBranch% %EXTREPO_URL% %EXTREPO_DIR% 2>&1'
        displayName: 'Fetch external repo'
        env:
          EXTREPO_URL: ${{parameters.extRepoUrl}}
          EXTREPO_DIR: ${{parameters.extRepoDir}}
          HelperBranch: ${{parameters.HelperBranch}}
        timeoutInMinutes: 0

      - task: CopyFiles@2
        displayName: 'Copy CodeSign files'
        inputs:
          SourceFolder: '${{parameters.extRepoDir}}/CodeSign'
          TargetFolder: '$(Build.BinariesDirectory)/CodeSign'

      - task: CopyFiles@2
        displayName: 'Copy RDMA'
        inputs:
          SourceFolder: '${{parameters.extRepoDir}}/ProtoSDK/RDMA'
          TargetFolder: '$(Build.BinariesDirectory)/ProtoSDK/RDMA'

      - task: PowerShell@2
        displayName: 'Run code sign script'
        inputs:
          targetType: filePath
          filePath: '$(Build.BinariesDirectory)/CodeSign/Execute-SignTestSuites.ps1'
          arguments: '-TestSuiteName $(test.testSuiteName)'
          workingDirectory: '$(Build.BinariesDirectory)/CodeSign'
          errorActionPreference: continue

      - task: CopyFiles@2
        displayName: 'Copy MSI' 
        inputs:
          SourceFolder: '$(Build.BinariesDirectory)/drop'
          Contents: '**\*.msi'
          TargetFolder: '$(Build.StagingDirectory)'
          OverWrite: true
          flattenFolders: true

      - task: PowerShell@2
        displayName: 'Verify CodeSign '
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            New-Item -Path "$(Build.BinariesDirectory)/Inputs" -ItemType Directory -Force
            Copy-Item -Path "$(Build.StagingDirectory)/*.msi" -Destination "$(Build.BinariesDirectory)/Inputs" -Recurse -Force
            New-Item -Path "$(Build.BinariesDirectory)/Results" -ItemType Directory -Force
            Get-ChildItem -Path "$(Build.BinariesDirectory)/Inputs" -Filter "*.msi" | Foreach-Object { $(Build.BinariesDirectory)/CodeSign/Test/CodeSignVerify.ps1 -MsiPath $_.FullName -ReportPath "$(Build.BinariesDirectory)/Results/$($_.Name).html" }
          errorActionPreference: continue

      - task: CopyFiles@2
        displayName: 'Copy Verify Results' 
        inputs:
          SourceFolder: '$(Build.BinariesDirectory)/Results'
          Contents: '*.html'
          TargetFolder: '$(Build.StagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish MSI and Result html'
        inputs:
          PathtoPublish: '$(Build.StagingDirectory)'
          timeoutInMinutes: 0
          condition: always()

      - ${{ if eq(parameters.enableRegression, 'true') }}:
        - task: CopyFiles@2
          displayName: 'Copy MSI' 
          inputs:
            SourceFolder: '$(Build.BinariesDirectory)/drop'
            Contents: '**'
            TargetFolder: '$(build.sharePath)/$(test.buildTag)'

        - task: jb.queue-build.queue-build-task.queue-build@2
          displayName: Run RDPServer_Local_Regression
          inputs:
            buildDefinitionName: 'RDPServer_Local_Regression'
            buildConfigurationType: json
            buildConfiguration: |
            {
              "default": {
                "sourceBranch": "staging",
                "parameters": {
                    "test.sourceBuildTag": $(test.buildTag)
                }
              }
            }
          condition: or(eq('${{ parameters.testSuiteName }}', $null), eq('${{ parameters.testSuiteName }}', 'RDPServer'))