parameters:
  extRepoUrl : ''
  extRepoDir : ''
  enableRegression: false
  HelperBranch : 'master'

jobs:
  - job:
    displayName: Code Sign and Verify
    pool: 
      name: TestSuiteESRPCodeSignPool
    workspace:
      clean: false
    timeoutInMinutes: 0

    steps:
      - ${{ if eq(parameters.enableRegression, 'true') }}:
        - task: CopyFiles@2
          displayName: 'Copy MSI to share' 
          inputs:
            SourceFolder: '$(Build.BinariesDirectory)/drop'
            Contents: '**'
            TargetFolder: '$(build.sharePath)/$(test.buildTag)'

        - task: jb.queue-build.queue-build-task.queue-build@2
          displayName: Run RDPServer_Local_Regression
          inputs:
            buildDefinitionName: 'RDPServer_Local_Regression'
            buildConfigurationType: json
            buildConfiguration: |
              {
                "sourceBranch": "staging",
                "parameters": {
                  "test.sourceBuildTag": $(test.buildTag)
                }
              }
              authToken: $(System.AccessToken)
          condition: or(eq(variables['test.testSuiteName'], '$null'), eq(variables['test.testSuiteName'], 'RDPServer'))