trigger: none 

variables:
  - group: External Repo Variables
  - name: test.enableRegression
    value: false

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: v-zhanh/CodeSignTemplates

jobs:
- job:
  displayName: Code Sign
  pool: 
    name: TestSuiteESRPCodeSignPool
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - template: pipelines/local/ESRPCodeSign-TestSuite-steps.yml@template
    parameters:
      extRepoUrl: $(extRepo.url)
      extRepoDir: $(extRepo.dir)
      TestSuiteName: $(test.testSuiteName)
      HelperBranch: $(test.helperBranch)

  - template: pipelines/local/ESRPCodeSign-TestSuite-Regression-steps.yml@template
    parameters:
        enableRegression: $(test.enableRegression)