trigger: none 

variables:
  - group: External Repo Variables

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: AzurePipelines

jobs:
- job:
  displayName: Code Sign
  pool: 
    name: TestSuiteESRPCodeSignPool
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - template: pipelines/CodeSign/ESRPCodeSign-TestSuite-steps.yml@template
    parameters:
      extRepoUrl: $(extRepo.url)
      extRepoDir: $(extRepo.dir)
      TestSuiteName: $(test.testSuiteName)
      HelperBranch: $(test.helperBranch)