trigger: none

variables:
  - group: InstallPrerequisitesVariable

jobs:
- job:
  displayName: InstallPrerequisites
  pool: 
    name: AzureAgents1
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - script: echo $(helperBranch)
            echo $(extRepo.dir)
            echo $(extRepo.url)
            echo $(ReleaseMSIPath)
            echo $(ReleasePathUserName)
            echo $(ReleasePathPwd)
    displayName: 'echo variables'

  - script: 'git clone --single-branch --progress -b $(helperBranch) %EXTREPO_URL% %EXTREPO_DIR% 2>&1'
    displayName: 'Fetch external repo'
    env:
      EXTREPO_URL: $(extRepo.url)
      EXTREPO_DIR: $(extRepo.dir)
    timeoutInMinutes: 0
  
  - task: PowerShell@2
    displayName: 'Run regression script'
    inputs:
      targetType: filePath
      filePath: $(Build.Repository.LocalPath)\_Helper\InstallPrerequisites\Setup-InstallEnvironment.ps1
      arguments: '-Workspace "$(Pipeline.Workspace)" -SourcePath "$(Build.Repository.LocalPath)" -ReleaseMSIPath %MSI_PATH% -ReleasePathUserName %MSI_USER% -ReleasePathPwd MSI_PWD'
    env:
      MSI_PATH: $(ReleaseMSIPath)
      MSI_USER: $(ReleasePathUserName)
      MSI_PWD: $(ReleasePathPwd)
    timeoutInMinutes: 0