trigger: none

variables:
  - group: InstallPrerequisitesVariable

jobs:
- job:
  displayName: InstallPrerequisites
  pool: 
    name: AzureAgents1
  workspace:
    clean: all
  timeoutInMinutes: 0

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: echo $(extRepo.url)
    displayName: 'Run a one-line script'

  - script: echo $(helperBranch)
            echo $(Build.Repository.LocalPath)
            echo $(Pipeline.Workspace)
    displayName: 'echo helperBranch'

  - script: 'git clone --single-branch --progress -b $(helperBranch) %EXTREPO_URL% %EXTREPO_DIR% 2>&1'
    displayName: 'Fetch external repo'
    env:
      EXTREPO_URL: $(extRepo.url)
      EXTREPO_DIR: $(extRepo.dir)
    timeoutInMinutes: 0