trigger: none 

variables:
  - group: External Repo Variables

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: v-xinzli/InstallPrerequisites2

jobs:
- job:
  displayName: Verify Pull Requests
  pool: 
    name: AzureAgents1
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - template: pipelines/local/PullRequestBuild-steps.yml@template
    parameters:
      extRepoUrl: $(extRepo.url)
      extRepoDir: $(extRepo.dir)





















trigger: none

variables:
  - group: InstallPrerequisitesVariable

jobs:
- job:
  displayName: InstallPrerequisites
  pool: 
    name: AzureAgents1
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - script: echo $(helperBranch)
                 $(extRepo.dir)
                 $(ReleaseMSIPath)
                 $(ReleaseMSIUserName)
    displayName: 'echo variables'

  - script: 'git clone --single-branch --progress -b $(helperBranch) %EXTREPO_URL% %EXTREPO_DIR% 2>&1'
    displayName: 'Fetch external repo'
    env:
      EXTREPO_URL: $(extRepo.url)
      EXTREPO_DIR: $(extRepo.dir)
    timeoutInMinutes: 0
  
  - task: PowerShell@2
    displayName: 'Run regression script'
    inputs:
      targetType: filePath
      filePath: $(Build.Repository.LocalPath)\_Helper\TestInstallPrerequisites\Setup-InstallEnvironment.ps1
      arguments: '-Workspace "$(Pipeline.Workspace)" -SourcePath "$(Build.Repository.LocalPath)" -ReleaseMSIPath "$(ReleaseMSIPath)" -ReleaseMSIUserName "$(ReleaseMSIUserName)" -ReleaseMSIPassword "$(ReleaseMSIPassword)"'
    timeoutInMinutes: 0