trigger: none

variables:
  - group: InstallPrerequisitesVariable

jobs:
- job:
  displayName: InstallPrerequisites
  pool: 
    name: AzureAgents1
  workspace:
    clean: all
  timeoutInMinutes: 0

  steps:
  - script: echo $(extRepo.url)
    displayName: 'Run a one-line script'

  - script: echo $(helperBranch)
            echo $(extRepo.dir)
            echo $(extRepo.url)
    displayName: 'echo helperBranch'

  - script: 'git clone --single-branch --progress -b $(helperBranch) %EXTREPO_URL% %EXTREPO_DIR% 2>&1'
    displayName: 'Fetch external repo'
    env:
      EXTREPO_URL: $(extRepo.url)
      EXTREPO_DIR: $(extRepo.dir)
    timeoutInMinutes: 0
  
  - task: PowerShell@2
    displayName: 'Run regression script'
    inputs:
      targetType: filePath
      filePath: $(Build.Repository.LocalPath)\InstallPrerequisites\Setup-InstallEnvironment.ps1
    timeoutInMinutes: 0