trigger: 
  batch : true
  branches:
    include: 
    - v-zhanh/TestSync

variables:
  - group: External Repo Variables

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: v-zhanh/syncSteps

jobs:
  - template: pipelines/Sync/Merge-Branch-steps.yml@template
    parameters:
        extRepoUrl: $(extRepo.url)
        extRepoDir: $(Build.BinariesDirectory)
        extRepoBranch: $(extRepo.helperBranch)    
        RemoteName: $(repo.RemoteName)
        RemoteUrl: $(repo.RemoteUrl)
        BranchesToMerge: $(repo.BranchesToMerge)