trigger: none 

variables:
  - name: testBranch
    value: 'WindowsProtocolTestSuites/WindowsProtocolTestSuites'
  - group: External Repo Variables

resources:
  repositories:
    - repository: template
      type: git
      name: $(testBranch)
      ref: v-zhanh/privatePipeline

jobs:
- job:
  displayName: Verify Pull Requests
  pool: 
    name: TestSuiteBuildPool
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - template: pipelines/ValidationPullRequest-Steps.yml@template
    parameters:
      extRepoUrl: $(extRepo.url)
      extRepoDir: $(extRepo.dir)