trigger: none 

variables:
  - name: branchName
    value: 'v-zhanh/privatePipeline'
  - group: External Repo Variables

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: $(branchName)

jobs:
- job:
  displayName: Verify Pull Requests
  pool: 
    name: TestSuiteBuildPool
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - template: pipelines/ValidationPullRequest-Steps.yml@template
    parameters:
      extRepoUrl: $(extRepo.url)
      extRepoDir: $(extRepo.dir)