parameters:
  extRepoUrl : ''
  extRepoDir : ''
  extRepoBranch : 'master'
  RemoteName: ''
  RemoteUrl: ''
  SyncBranch: ''
  MirrorBranch: ''

jobs:
  - job:
    displayName: Sync Branch Between Repo
    pool: 
      name: TestSuiteBuildPool
    workspace:
      clean: all
    timeoutInMinutes: 0

    steps:
      - script: echo "extRepoUrl ${{parameters.extRepoUrl}}"
                echo "extRepoDir ${{parameters.extRepoDir}"
        displayName: 'Show parameters'
        
      - script: 'git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" -b ${{parameters.extRepoBranch}} ${{parameters.extRepoUrl}} ${{parameters.extRepoDir}} 2>&1'
        displayName: 'Fetch external repo'
        timeoutInMinutes: 0

      - task: PowerShell@2
        displayName: 'Sync-Branch-Between-Repo'
        inputs:
          targetType: filePath
          filePath: ${{parameters.extRepoDir}}\GitSync\Sync-Branch-Between-Repo.ps1
          arguments: '-RemoteName ${{parameters.RemoteName}} -RemoteUrl ${{parameters.RemoteUrl}} -SyncBranch ${{parameters.SyncBranch}} -MirrorBranch ${{parameters.MirrorBranch}}'
          timeoutInMinutes: 0    

        