parameters:
  extRepoUrl : ''
  extRepoDir : ''
  extRepoBranch : 'master'
  RemoteName: ''
  RemoteUrl: ''
  SyncBranch: ''
  MirrorBranch: ''

jobs:
  - job:
    displayName: Sync Branch Between Repo
    pool: 
      name: TestSuiteBuildPool
    workspace:
      clean: all
    timeoutInMinutes: 0

    steps:
      - script: echo "extRepoUrl ${{parameters.extRepoUrl}}"
                echo "extRepoDir ${{parameters.extRepoDir}"
        displayName: 'Show parameters'
        
      - script: 'git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" -b %EXTREPO_Branch% %EXTREPO_URL% %EXTREPO_DIR% 2>&1'
        displayName: 'Fetch external repo'
        env:
          EXTREPO_URL: ${{parameters.extRepoUrl}}
          EXTREPO_DIR: ${{parameters.extRepoDir}}
          EXTREPO_Branch: ${{parameters.extRepoBranch}}
        timeoutInMinutes: 0

      - task: PowerShell@2
        displayName: 'Sync-Branch-Between-Repo'
        inputs:
          targetType: filePath
          filePath: $(extRepo.dir)\GitSync\Sync-Branch-Between-Repo.ps1
          arguments: '-RemoteName ${{parameters.RemoteName}} -RemoteUrl ${{parameters.RemoteUrl}} -SyncBranch ${{parameters.SyncBranch}} -MirrorBranch ${{parameters.MirrorBranch}}'
          timeoutInMinutes: 0    

        